### ISSUE TITLE
URIs with embedded credentials do not work

### ISSUE THREAD

**Issue by sieppl** [searchkit/searchkit-starter-app#2]
Setting up an instance with an URI like this one:
`this.searchkit = new SearchkitManager("https://username:password@myproject-3586754631.eu-west-1.bonsaisearch.net")`

When the SearchKitManager is sending requests to ES, the credentials are removed from the URI and ES is responding with an 401.  So request are going to `https://myproject-3586754631.eu-west-1.bonsaisearch.net` instead of `https://username:password@myproject-3586754631.eu-west-1.bonsaisearch.net`

You can create a free sandbox ES cloud instance [here](https://bonsai.io/) in order to reproduce the error.

**Comment by tecmusti** [comment]
Try this:
`this.searchkit = new SearchkitManager('https://myproject-3586754631.eu-west-1.bonsaisearch.net', {basicAuth:'username:password'})`
